apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: gop-fileserver
spec:
  containers:
  - image: kodekloud/fileserver
    name: fileserver
    volumeMounts:
    - name: data-store
      mountPath: /web
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
